### ISSUE TITLE
Calışmıyor.

### ISSUE THREAD

**Issue by sada586** [OzgeKocaoglu/prometheus#2]
Sadece tanıtım texti özenilmiş hatta ona daha fazla çaba verilmiş. Hiçbir ozellik çalışmamakta.

**Comment by OzgeKocaoglu** [comment]
Hangi deployment metodunu denediniz? Çalışması için bir adet mongodb'den database api key'ine ihtiyacınız bulunmakta. Henüz readme dosyasını bitiremediğim için nasıl deployment yapılacağını yazamamıştım. "Tanıtım text"i dediğiniz text eksik olduğu için sanırım deploy edemediniz.
